config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
  resources :users, only: [:edit, :update]
  resources :products do
    resources :items
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :items, dependent: :destroy
  accepts_nested_attributes_for :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all
  end

  def show
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path, notice: "商品が追加されました"
    else
      redirect_to new_product_item_path, alert: "入力項目が不足しています。再度登録してください"
    end
  end

  def edit
  end

  def update
  end

  def destroy
    if @item.destroy
      redirect_to root_path, notice: "商品が削除されました"
    else
      redirect_to product_path(@product.id), alert: "削除に失敗しました"
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :image, :all_number, :sold_number, :memo, :product_id)
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to new_product_item_path(@product.id), notice: "プロダクトが追加されました"
    else
      redirect_to new_product_path, alert: "入力項目が不足しています。再度出品してください"
    end
  end

  def edit
  end

  def update
  end

  def destroy
    if @product.destroy
      redirect_to root_path, notice: "プロダクトが削除されました"
    else
      redirect_to product_path(@product.id), alert: "削除に失敗しました"
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :image, :description, :memo, :start, :end)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/index.html.haml
.Contents
  .Contents__index-side
    = render partial: "./products/sidebar"
  .Contents__index-main
    = render partial: "./products/main-header"
    .default-container
    - @items.each do |item|
      .product
        .product__container
          %h1.product__container__name
            = item.name
        .product__main-contents
          .product__main-contents__photo
            .product__main-contents__photo__photo-main
              = image_tag item.image
    
        .product__description
          %p.product__description__text
            仕入れ総数
            = item.all_number
          %p.product__description__text
            販売数
            = item.sold_number
          %p.product__description__text
            残数
            = item.all_number - item.sold_number
          %p.product__description__text
            メモ
            = item.memo

app/views/items/new.html.haml
.single-container
  %header.single-container__header
    %h1
      = link_to root_path do
        戻る

  %main.single-main
    %section.l-single-container
      .sell-container
        %h2.sell-container__header 商品の情報を入力
      = form_for @item ,url: {:action => :create} do |item|
        .sell-container__sell-form
 
          .sell-container__sell-form__sell-content
            = item.label :name do
              商品名
              %span.form-require 必須
            %div
              = item.text_field :name, class: "input-default", placeholder: "商品名  (必須 40文字まで)"

          .sell-container__sell-form__sell-content
            = item.label :image do
              画像
            = item.file_field :image

          .sell-container__sell-form__sell-content
            = item.label :all_number do
              仕入れ総数
              %span.form-require 必須
            = item.number_field :all_number, class: "textarea-default"

          .sell-container__sell-form__sell-content
            = item.label :sold_number do
              販売数
              %span.form-require 必須
            = item.number_field :sold_number, class: "textarea-default"

          .sell-container__sell-form__sell-content
            = item.label :memo do
              メモ
              %span.form-require 必須
            = item.text_field :memo, class: "textarea-default", rows: "5", placeholder: "メモ  (必須 40文字まで)"

            = item.submit "登録", class: "btn-default"
            = link_to "もどる", root_path, class: "btn-default btn-gray"
  %footer
    .default-container
      .single

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SdrManage
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/products/_main-header.html.haml
.Contents__index-main__main-header
  .Contents__index-main__main-header__current-group
    .Contents__index-main__main-header__current-group__name
      = link_to 'SDR Sales Staff', root_path
    .Contents__index-main__main-header__current-group__member-list
      .Contents__index-main__main-header__current-group__member-list__member
        -# - @group.group_users.each do |group_user|
        -#   = group_user.user.name
  .Contents__index-main__main-header__edit-btn
    -# = link_to "Edit", edit_group_path(@group)

app/views/products/_message.html.haml
.Contents__index-main__messages__message
  .Contents__index-main__messages__message__upper-info
    .Contents__index-main__messages__message__upper-info__user
      プロダクト情報
    -#   = message.user.name
    .Contents__index-main__messages__message__upper-info__date
    -#   = message.created_at.strftime("%Y/%m/%d %H:%M")
  .Contents__index-main__messages__message__text
    %p.lower-message__content
      小腹サポート

app/views/products/_sidebar.html.haml
.side-bar
  .header
    %h3.header__name
      = current_user.name
    -#   = current_user.name
    %ul.header__lists
      %li.list
        = link_to new_product_path do
          = fa_icon 'pencil-square-o', class: 'icon'
      %li.list
        = link_to edit_user_path(current_user) do
          = fa_icon 'cog', class: 'icon'

  %ul.items
    %li.item
      .item__name
        ヒアリングシート
      .item__message
        = link_to 'ヒアリング内容を書き込む', "https://docs.google.com/spreadsheets/d/1UngIsk_uqIDs2Wj3Zx6d29Qt6-6ox4yVq_uoOfR67jg/edit?usp=sharing", target: :_blank
      
      .item__name
        売り上げ報告
      .item__message
      -# = link_to ""
        その日の売り上げを報告する
     
      .item__name
        販売マニュアル
      .item__message
        -# = link_to ""
        販売マニュアルを読む
     
      .item__name
        在庫管理
      .item__message
        -# = link_to ""
        在庫を確認する
    
      .item__name
        プロダクト追加
      .item__message
        = link_to 'プロダクトを追加する', new_product_path(current_user)

      .item__name
        シフト
      .item__message
        -# = link_to ""
        シフトを確認する

app/views/products/index.html.haml
.Contents
  .Contents__index-side
    = render partial: "sidebar"
  .Contents__index-main
    = render partial: "main-header"
    .Contents__index-main__title
      Product Information
    - @products.each do |product|
      .Contents__index-main__product
        .Contents__index-main__product__content
          = image_tag product.image
        .Contents__index-main__product__content
          商品名：
          = product.name
        .Contents__index-main__product__content
          展示開始時期：
          = product.start
        .Contents__index-main__product__content
          展示終了時期：
          = product.end
        .Contents__index-main__product__content
          = link_to '詳細',product_path(product)

app/views/products/new.html.haml
.single-container
  %header.single-container__header
    %h1
      = link_to root_path do
        戻る

  %main.single-main
    %section.l-single-container
      .sell-container
        %h2.sell-container__header 商品の情報を入力
      = form_for @product do |product|
        .sell-container__sell-form
 
          .sell-container__sell-form__sell-content
            = product.label :name do
              商品名
              %span.form-require 必須
            %div
              = product.text_field :name, class: "input-default", placeholder: "商品名  (必須 40文字まで)"

          .sell-container__sell-form__sell-content
            = product.label :image do
              画像
            = product.file_field :image

          .sell-container__sell-form__sell-content
            = product.label :description do
              商品の説明
              %span.form-require 必須
            = product.text_area :description, class: "textarea-default", rows: "5", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）"
          .sell-container__sell-form__sell-content
            = product.label :memo do
              商品の説明
              %span.form-require 必須
            = product.text_area :memo, class: "textarea-default", rows: "5", placeholder: "商品メモ"

          .sell-container__sell-form__sell-content
            = product.label :start do
              商品の説明
              %span.form-require 必須
            = product.date_field :start, class: "textarea-default", rows: "5"

          .sell-container__sell-form__sell-content
            = product.label :end do
              商品の説明
              %span.form-require 必須
            = product.date_field :end, class: "textarea-default", rows: "5"

            = product.submit "種類登録へ", class: "btn-default"
            = link_to "もどる", root_path, class: "btn-default btn-gray"
  %footer
    .default-container
      .single

app/views/products/show.html.haml
.Contents
  .Contents__index-side
    = render partial: "sidebar"
  .Contents__index-main
    = render partial: "main-header"
    .default-container
      .product
        .product__container
          %h1.product__container__name
            = @product.name
        .product__main-contents
          .product__main-contents__photo
            .product__main-contents__photo__photo-main
              = image_tag @product.image
    
        .product__description
          %p.product__description__text
            詳細：
            = @product.description
          %p.product__description__text
            メモ：
            = @product.memo
          %p.product__description__text
            販売開始：
            = @product.start
          %p.product__description__text
            販売終了：
            = @product.end
          %p.product__description__text
            = link_to '在庫へ', product_items_path(@product.id)

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'